TRAIN:
  BATCH_SIZE: 128
  CHECKPOINT_PERIOD: 20
MULTI_VIEWS_TRANSFORMS:
  GLOBAL_CROPS_SCALE: [0.14, 1.0]
  LOCAL_CROPS_SCALE: [0.05, 0.14]
  LOCAL_CROPS_NUMBER: 6  
  RANDOM_HORIZONTAL_FLIP_PROB: [0.5, 0.5]
  GAUSSIAN_BLUR_PROB: [1.0, 0.1, 0.5] # global_1, global_2, local
  COLOR_JITTER_PROB: [0.8, 0.8]
  COLOR_JITTER_INTENSITY: [0.4, 0.4, 0.2, 0.1]
  GREYSCALE_PROB: [0.2, 0.2]
  CROP_PROB: [1.0, 1.0]
  LOCAL_CROP_SIZE: 96
  GLOBAL_CROP_SIZE: 224
  SOLARIZATION_PROB: [0.0, 0.2]
  CROPS_FOR_ASSIGN: [0, 1]
  NMB_CROPS: [2, 6]
  LAMBDAS: [0.142857, 0.857143]
MODEL:
  BACKBONE_ARCH: mobilenet_v2
  MODEL_MOMENTUM: 0.996
MOCO:
  GLOBAL_ONLY: False
  TEMPERATURE: 0.2
  QUEUE_LENGTH: 65536
  MOMENTUM: 0.999
  OUTPUT_DIM: 128
  HIDDEN_SIZE: 2048
  NUM_LAYERS: 2
  USE_BN_IN_HEAD: False
SOLVER:
  OPTIMIZING_METHOD: LARS
  WEIGHT_DECAY: 1.0e-6
  WEIGHT_DECAY_END: 1.0e-6
  TOTAL_EPOCHS: 200
  BASE_LR: 0.48
  MIN_LR: 0.0048
  MOMENTUM: 0.9
  CLIP_GRAD: 0.0
LOG_STEP: 20
SSL_METHOD: MOCO
STAGE: TRAIN 
DISTRIBUTED: True
SEED: 0
DIST_BACKEND: 'nccl'
N_NODES: 1
WORLD_SIZE: 1
NODE_RANK: 0
DIST_URL: "env://"
WORKERS: 4
USE_FP16: False