TRAIN:
  BATCH_SIZE: 128
  CHECKPOINT_PERIOD: 20
MULTI_VIEWS_TRANSFORMS:
  GLOBAL_CROPS_SCALE: [0.14, 1.0]
  LOCAL_CROPS_SCALE: [0.05, 0.14]
  LOCAL_CROPS_NUMBER: 6  
  RANDOM_HORIZONTAL_FLIP_PROB: [0.5, 0.5]
  GAUSSIAN_BLUR_PROB: [0.5, 0.5, 0.5] # global_1, global_2, local
  COLOR_JITTER_PROB: [0.8, 0.8]
  COLOR_JITTER_INTENSITY: [0.8, 0.8, 0.8, 0.2]
  GREYSCALE_PROB: [0.2, 0.2]
  CROP_PROB: [1.0, 1.0]
  LOCAL_CROP_SIZE: 96
  GLOBAL_CROP_SIZE: 224
  SOLARIZATION_PROB: [0.0, 0.0]
  CROPS_FOR_ASSIGN: [0, 1]
  NMB_CROPS: [2, 6]
  LAMBDAS: [0.142857, 0.857143]
MODEL:
  BACKBONE_ARCH: mobilenet_v2
SOLVER:
  OPTIMIZING_METHOD: LARS
  WEIGHT_DECAY: 1.0e-6
  WEIGHT_DECAY_END: 1.0e-6
  TOTAL_EPOCHS: 200
  WARMUP_EPOCHS: 10
  START_WARMUP: 0.075
  BASE_LR: 0.3
  MOMENTUM: 0.9
  MIN_LR: 0.0048
SWAV:
  FREEZE_PROTOTYPES_EPOCHS: 1
  EPOCH_QUEUE_STARTS: 15 
  TEMPERATURE: 0.1 
  EPSILON: 0.05
  SINKHORN_ITERATIONS: 3
  NMB_PROTOTYPES: 3000 
  QUEUE_LENGTH: 3840
  OUTPUT_DIM: 128
  HIDDEN_SIZE: 4096
  NUM_LAYERS: 2
  USE_BN_IN_HEAD: True
SSL_METHOD: SWAV
LOG_STEP: 20
# stage from [TRAIN, VAL, TEST, FT]
STAGE: TRAIN 
DISTRIBUTED: True
SEED: 0
DIST_BACKEND: 'nccl'
N_NODES: 1
WORLD_SIZE: 1
NODE_RANK: 0
DIST_URL: "env://"
WORKERS: 4
USE_FP16: False