TRAIN:
  BATCH_SIZE: 128
  CHECKPOINT_PERIOD: 20
MULTI_VIEWS_TRANSFORMS:
  GLOBAL_CROPS_SCALE: [0.25, 1.0]
  LOCAL_CROPS_SCALE: [0.05, 0.25]
  LOCAL_CROPS_NUMBER: 10  
  RANDOM_HORIZONTAL_FLIP_PROB: [0.5, 0.5]
  GAUSSIAN_BLUR_PROB: [1.0, 0.1, 0.5] # global_1, global_2, local
  COLOR_JITTER_PROB: [0.8, 0.8]
  COLOR_JITTER_INTENSITY: [0.4, 0.4, 0.2, 0.1]
  GREYSCALE_PROB: [0.2, 0.2]
  CROP_PROB: [1.0, 1.0]
  LOCAL_CROP_SIZE: 96
  GLOBAL_CROP_SIZE: 224
  SOLARIZATION_PROB: [0.0, 0.2]
  CROPS_FOR_ASSIGN: [0, 1]
  NMB_CROPS: [2, 10]
  LAMBDAS: [0.090909, 0.909091]
MODEL:
  BACKBONE_ARCH: vit_tiny
  MODEL_MOMENTUM: 0.996
VIT:
  DROP_PATH_RATE: 0.1
  PATCH_SIZE: 16
DINOHead:
  OUTPUT_DIM: 65536
  USE_BN_IN_HEAD: False
  NORM_LAST_YEAR: False
DINO:
  WARMUP_TEACHER_TEMP_EPOCHS: 30
SOLVER:
  OPTIMIZING_METHOD: AdamW
  WEIGHT_DECAY: 0.04
  WEIGHT_DECAY_END: 0.4
  TOTAL_EPOCHS: 200
  WARMUP_EPOCHS: 10
  BASE_LR: 0.0005
  MIN_LR: 0.00001
  MOMENTUM: 0.9
  CLIP_GRAD: 0.0
  FREEZE_LAST_LAYER: 1
LOG_STEP: 20
# stage from [TRAIN, VAL, TEST, FT]
SSL_METHOD: DINO
STAGE: TRAIN 
DISTRIBUTED: True
SEED: 0
DIST_BACKEND: 'nccl'
N_NODES: 1
WORLD_SIZE: 1
NODE_RANK: 0
DIST_URL: "env://"
WORKERS: 4
USE_FP16: False
NUM_GPUS_PER_NODE: 8