_BASE_: "../Base-RCNN-C4-BN.yaml"
MODEL:
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_ON: False
  WEIGHTS: "" #"ckpts/d2_det/resnet18_detectron2.pkl"
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
  ROI_HEADS:
    NUM_CLASSES: 20
INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('voc_2007_trainval', 'voc_2012_trainval')
  TEST: ('voc_2007_test',)
SOLVER:
  STEPS: (36000, 44000)
  MAX_ITER: 48000
  WARMUP_ITERS: 100
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
OUTPUT_DIR: './logs/voc-r18-c4'